// This file was generated by Prisma, and assumes you have installed the following:
// npm install --save-dev prisma dotenv
import "dotenv/config";
import { defineConfig, env } from "prisma/config";

export default defineConfig({
  schema: "prisma/schema.prisma",
  migrations: {
    path: "prisma/migrations",
    seed: "node prisma/seed.js",
  },
  engine: "classic",
  datasource: {
    // url: "postgresql://postgres.inceivyzvezxqsdhayaw:ZT1ZDxEtEZttqFlE@aws-1-ap-northeast-1.pooler.supabase.com:6543/postgres?pgbouncer=true",
    // directUrl: "postgresql://postgres.inceivyzvezxqsdhayaw:ZT1ZDxEtEZttqFlE@aws-1-ap-northeast-1.pooler.supabase.com:5432/postgres"
    url: process.env["DATABASE_URL"],
    // directUrl: process.env["DIRECT_URL"], // Tambahkan ini
  },
});